Two years of acculated changes

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -20,6 +20,7 @@ xterm*|rxvt*)
     ;;
 esac
 
+
 # enable color support of ls and also add handy aliases
 if [ -x /usr/bin/dircolors ]; then
     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
@@ -56,3 +57,29 @@ eval "$(direnv hook bash)"
 
 export PATH="$HOME/.rbenv/bin:$PATH"
 eval "$(rbenv init -)"
+
+# on macos your ssh keys need to be re-added on reboot
+ssh-add -K
+
+function prompt_command() {
+   local EXIT="$?"
+   PS1=""
+
+    local RCol='\[\e[0m\]'
+    local Red='\[\e[0;31m\]'
+    local Gre='\[\e[0;32m\]'
+    local BYel='\[\e[1;33m\]'
+    local BBlu='\[\e[1;34m\]'
+    local Pur='\[\e[0;35m\]'
+
+    if [ $EXIT -ne 0 ]; then
+        PS1+="${Red}❌ $EXIT \u${RCol}"      # Add red if exit code non 0
+    else
+        PS1+="${Gre}✅ \u${RCol}"
+    fi
+
+    PS1+="${RCol}@${BBlu}\h ${Pur}\W${BYel}$ ${RCol}"
+}
+export PROMPT_COMMAND=prompt_command
+
+[ -f ~/.fzf.bash ] && source ~/.fzf.bash
